# These are supported funding model platforms

patreon: swordfish90
custom: ['https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=flscogna%40gmail.com&item_name=Support+Lemuroid&currency_code=EUR&source=url']
